<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE softwareLibre [
  <!ELEMENT softwareLibre (licencias, aplicaciones)>
  <!ELEMENT licencias (licencia*)>
  <!ELEMENT licencia EMPTY>
  <!ELEMENT aplicaciones (aplicacion*)>
  <!ELEMENT aplicacion (version*)>
  <!ELEMENT version EMPTY>
  <!ATTLIST licencia nombre CDATA #REQUIRED>
  <!ATTLIST aplicacion nombre ID #REQUIRED>
  <!ATTLIST version nombre CDATA #REQUIRED>
  <!ATTLIST version licencia (open_v2|gpl_v2|bsd2) #REQUIRED>
  <!ATTLIST version fechaPublicación CDATA #REQUIRED>
]>
<softwareLibre>
  <licencias>
    <licencia nombre="GPL v2" />
    <licencia nombre="BSD2" />
    <licencia nombre="Apache v2" />
  </licencias>
  <aplicaciones>
    <aplicacion nombre="Inkscape">
      <version nombre="0.47" licencia="open_v2" fechaPublicación="17/08/2010" />
      <version nombre="0.48" licencia="gpl_v2" fechaPublicación="17/08/2010" />
      <version nombre="0.48.2" licencia="gpl_v2" fechaPublicación="14/08/2011" />
    </aplicacion>
    <aplicacion nombre="PostgreSQL">
      <version nombre="9.1.0" licencia="bsd2" fechaPublicación="15/09/2011" />
      <version nombre="9.1.3" licencia="bsd2" fechaPublicación="" />
    </aplicacion>
  </aplicaciones>
</softwareLibre>